apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway
  namespace: gateway
  labels:
    app.kubernetes.io/name: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: api
