mod error;
mod extractors;
mod middleware;
mod router;
mod routes;
mod state;

use std::net::SocketAddr;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    gateway_observability::init_tracing();

    let cmd = parse_cli();

    match cmd {
        CliCommand::Config => run_config_wizard().await,
        CliCommand::Profile => {
            let config = state::AppConfig::load();
            println!("AI Gateway SOLO");
            println!("===============");
            println!("Active profile: {}", config.profile.display_name());
            println!("  Description: {}", config.profile.description());
            println!("  Strategy:    {}", config.profile.default_strategy());
            println!("\nRun `gateway-solo config` to change your profile.");
            Ok(())
        }
        CliCommand::Serve => run_server().await,
    }
}

#[derive(Debug)]
enum CliCommand {
    Config,
    Profile,
    Serve,
}

fn parse_cli() -> CliCommand {
    let args: Vec<String> = std::env::args().collect();
    match args.get(1).map(|s| s.as_str()) {
        Some("config") => CliCommand::Config,
        Some("profile") => CliCommand::Profile,
        Some("serve") | Some("start") | None => CliCommand::Serve,
        Some(other) => {
            eprintln!("Unknown command: {}", other);
            eprintln!("Usage: gateway-solo [config|profile|serve]");
            std::process::exit(1);
        }
    }
}

async fn run_config_wizard() -> anyhow::Result<()> {
    use std::io::{self, Write};

    println!("AI Gateway SOLO — Configuration Wizard");
    println!("======================================");
    println!();

    let profiles = gateway_core::profiles::RoutingProfile::all_profiles();
    println!("Choose a routing profile:");
    for (i, p) in profiles.iter().enumerate() {
        println!("  {}. {} — {}", i + 1, p.display_name(), p.description());
    }
    println!();
    print!("Enter choice (1-{}): ", profiles.len());
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let choice: usize = input
        .trim()
        .parse::<usize>()
        .unwrap_or(1)
        .saturating_sub(1)
        .min(profiles.len() - 1);
    let selected = profiles[choice];

    println!("\nSelected: {}", selected.display_name());
    println!("\nSaving to gateway-solo.toml...");

    let toml = format!(
        r#"# AI Gateway SOLO configuration
# Auto-generated by config wizard

profile = "{}"
"#,
        selected.config_key()
    );

    std::fs::write("gateway-solo.toml", toml)?;
    println!("Configuration saved to gateway-solo.toml");
    println!("\nStart the server with: gateway-solo serve");

    Ok(())
}

async fn run_server() -> anyhow::Result<()> {
    let _metrics_handle = gateway_observability::metrics::init_metrics();
    tracing::info!("Prometheus metrics initialized at /metrics");

    let state = state::AppState::from_env().await?;

    let app = router::build_router(state.clone());

    let port = std::env::var("PORT")
        .ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(8080);
    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    tracing::info!("gateway-solo listening on {}", addr);
    tracing::info!("Database: {}", state.config.database_url);
    tracing::info!("Profile:  {}", state.config.profile.display_name());

    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(listener, app).await?;

    Ok(())
}
